package pojo;

// Generated 2017-9-20 13:42:34 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * Tannouncement generated by hbm2java
 */
public class Tannouncement implements java.io.Serializable {

	private BigDecimal id;
	private Tuser tuserByCreatuser;
	private Tuser tuserByModifyuser;
	private String anntitle;
	private String anncontext;
	private Date creattime;
	private Date modifytime;

	public Tannouncement() {
	}

	public Tannouncement(BigDecimal id) {
		this.id = id;
	}

	public Tannouncement(BigDecimal id, Tuser tuserByCreatuser,
			Tuser tuserByModifyuser, String anntitle, String anncontext,
			Date creattime, Date modifytime) {
		this.id = id;
		this.tuserByCreatuser = tuserByCreatuser;
		this.tuserByModifyuser = tuserByModifyuser;
		this.anntitle = anntitle;
		this.anncontext = anncontext;
		this.creattime = creattime;
		this.modifytime = modifytime;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Tuser getTuserByCreatuser() {
		return this.tuserByCreatuser;
	}

	public void setTuserByCreatuser(Tuser tuserByCreatuser) {
		this.tuserByCreatuser = tuserByCreatuser;
	}

	public Tuser getTuserByModifyuser() {
		return this.tuserByModifyuser;
	}

	public void setTuserByModifyuser(Tuser tuserByModifyuser) {
		this.tuserByModifyuser = tuserByModifyuser;
	}

	public String getAnntitle() {
		return this.anntitle;
	}

	public void setAnntitle(String anntitle) {
		this.anntitle = anntitle;
	}

	public String getAnncontext() {
		return this.anncontext;
	}

	public void setAnncontext(String anncontext) {
		this.anncontext = anncontext;
	}

	public Date getCreattime() {
		return this.creattime;
	}

	public void setCreattime(Date creattime) {
		this.creattime = creattime;
	}

	public Date getModifytime() {
		return this.modifytime;
	}

	public void setModifytime(Date modifytime) {
		this.modifytime = modifytime;
	}

}
