package pojo;

// Generated 2017-9-20 13:42:34 by Hibernate Tools 3.2.2.GA

import  java.lang.Long;

/**
 * Tarea generated by hbm2java
 */
public class Tarea implements java.io.Serializable {

	private java.lang.Long id;
	private String name;
	private java.lang.Long pid;

	public Tarea() {
	}

	public Tarea(java.lang.Long id) {
		this.id = id;
	}

	public Tarea(java.lang.Long id, String name, java.lang.Long pid) {
		this.id = id;
		this.name = name;
		this.pid = pid;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public java.lang.Long getPid() {
		return this.pid;
	}

	public void setPid(java.lang.Long pid) {
		this.pid = pid;
	}

}
