package pojo;

// Generated 2017-9-20 13:42:34 by Hibernate Tools 3.2.2.GA

 
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tcategory generated by hbm2java
 */
public class Tcategory implements java.io.Serializable {

	private java.lang.Long id;
	private Tuser tuserByCreatuser;
	private Tuser tuserByModifyuser;
	private String catename;
	private Date createtime;
	private Date modifytime;
	private Set tcategoryseconds = new HashSet(0);

	public Tcategory() {
	}

	public Tcategory(java.lang.Long id) {
		this.id = id;
	}

	public Tcategory(java.lang.Long id, Tuser tuserByCreatuser,
			Tuser tuserByModifyuser, String catename, Date createtime,
			Date modifytime, Set tcategoryseconds) {
		this.id = id;
		this.tuserByCreatuser = tuserByCreatuser;
		this.tuserByModifyuser = tuserByModifyuser;
		this.catename = catename;
		this.createtime = createtime;
		this.modifytime = modifytime;
		this.tcategoryseconds = tcategoryseconds;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public Tuser getTuserByCreatuser() {
		return this.tuserByCreatuser;
	}

	public void setTuserByCreatuser(Tuser tuserByCreatuser) {
		this.tuserByCreatuser = tuserByCreatuser;
	}

	public Tuser getTuserByModifyuser() {
		return this.tuserByModifyuser;
	}

	public void setTuserByModifyuser(Tuser tuserByModifyuser) {
		this.tuserByModifyuser = tuserByModifyuser;
	}

	public String getCatename() {
		return this.catename;
	}

	public void setCatename(String catename) {
		this.catename = catename;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Date getModifytime() {
		return this.modifytime;
	}

	public void setModifytime(Date modifytime) {
		this.modifytime = modifytime;
	}

	public Set getTcategoryseconds() {
		return this.tcategoryseconds;
	}

	public void setTcategoryseconds(Set tcategoryseconds) {
		this.tcategoryseconds = tcategoryseconds;
	}

}
