package pojo;

// Generated 2017-9-20 13:42:34 by Hibernate Tools 3.2.2.GA

import java.lang.Long;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tcategorysecond generated by hbm2java
 */
public class Tcategorysecond implements java.io.Serializable {

	private java.lang.Long id;
	private Tuser tuser;
	private Tcategory tcategory;
	private String catesname;
	private java.lang.Long creatuser;
	private Date creattime;
	private Date modifytime;
	private Set tgoodses = new HashSet(0);

	public Tcategorysecond() {
	}

	public Tcategorysecond(java.lang.Long id) {
		this.id = id;
	}

	public Tcategorysecond(java.lang.Long id, Tuser tuser, Tcategory tcategory,
			String catesname, java.lang.Long creatuser, Date creattime,
			Date modifytime, Set tgoodses) {
		this.id = id;
		this.tuser = tuser;
		this.tcategory = tcategory;
		this.catesname = catesname;
		this.creatuser = creatuser;
		this.creattime = creattime;
		this.modifytime = modifytime;
		this.tgoodses = tgoodses;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public Tuser getTuser() {
		return this.tuser;
	}

	public void setTuser(Tuser tuser) {
		this.tuser = tuser;
	}

	public Tcategory getTcategory() {
		return this.tcategory;
	}

	public void setTcategory(Tcategory tcategory) {
		this.tcategory = tcategory;
	}

	public String getCatesname() {
		return this.catesname;
	}

	public void setCatesname(String catesname) {
		this.catesname = catesname;
	}

	public java.lang.Long getCreatuser() {
		return this.creatuser;
	}

	public void setCreatuser(java.lang.Long creatuser) {
		this.creatuser = creatuser;
	}

	public Date getCreattime() {
		return this.creattime;
	}

	public void setCreattime(Date creattime) {
		this.creattime = creattime;
	}

	public Date getModifytime() {
		return this.modifytime;
	}

	public void setModifytime(Date modifytime) {
		this.modifytime = modifytime;
	}

	public Set getTgoodses() {
		return this.tgoodses;
	}

	public void setTgoodses(Set tgoodses) {
		this.tgoodses = tgoodses;
	}

}
