package pojo;

// Generated 2017-9-20 13:42:34 by Hibernate Tools 3.2.2.GA

import java.lang.Long;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tcustomer generated by hbm2java
 */
public class Tcustomer implements java.io.Serializable {

	private java.lang.Long id;
	private String familyname;
	private String realname;
	private String loginname;
	private String password;
	private String email;
	private java.lang.Long sex;
	private String picurl;
	private String hobby;
	private Date birthday;
	private Date regtime;
	private java.lang.Long isuse;
	private Set torders = new HashSet(0);
	private Set tcarts = new HashSet(0);

	public Tcustomer() {
	}

	public Tcustomer(java.lang.Long id) {
		this.id = id;
	}

	public Tcustomer(java.lang.Long id, String familyname, String realname,
			String loginname, String password, String email, java.lang.Long sex,
			String picurl, String hobby, Date birthday, Date regtime,
			java.lang.Long isuse, Set torders, Set tcarts) {
		this.id = id;
		this.familyname = familyname;
		this.realname = realname;
		this.loginname = loginname;
		this.password = password;
		this.email = email;
		this.sex = sex;
		this.picurl = picurl;
		this.hobby = hobby;
		this.birthday = birthday;
		this.regtime = regtime;
		this.isuse = isuse;
		this.torders = torders;
		this.tcarts = tcarts;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public String getFamilyname() {
		return this.familyname;
	}

	public void setFamilyname(String familyname) {
		this.familyname = familyname;
	}

	public String getRealname() {
		return this.realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public String getLoginname() {
		return this.loginname;
	}

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public java.lang.Long getSex() {
		return this.sex;
	}

	public void setSex(java.lang.Long sex) {
		this.sex = sex;
	}

	public String getPicurl() {
		return this.picurl;
	}

	public void setPicurl(String picurl) {
		this.picurl = picurl;
	}

	public String getHobby() {
		return this.hobby;
	}

	public void setHobby(String hobby) {
		this.hobby = hobby;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public Date getRegtime() {
		return this.regtime;
	}

	public void setRegtime(Date regtime) {
		this.regtime = regtime;
	}

	public java.lang.Long getIsuse() {
		return this.isuse;
	}

	public void setIsuse(java.lang.Long isuse) {
		this.isuse = isuse;
	}

	public Set getTorders() {
		return this.torders;
	}

	public void setTorders(Set torders) {
		this.torders = torders;
	}

	public Set getTcarts() {
		return this.tcarts;
	}

	public void setTcarts(Set tcarts) {
		this.tcarts = tcarts;
	}

}
