package pojo;

// Generated 2017-9-20 13:42:34 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * Tgoods generated by hbm2java
 */
public class Tgoods implements java.io.Serializable {

	private BigDecimal id;
	private Tuser tuserByCreatuser;
	private Tuser tuserByModifyuser;
	private Tcategorysecond tcategorysecond;
	private String goodsname;
	private BigDecimal price;
	private BigDecimal sucount;
	private BigDecimal transprice;
	private String remaintime;
	private BigDecimal salecount;
	private BigDecimal sumsalecount;
	private String goodsqutity;
	private String belongto;
	private BigDecimal hitcount;
	private String gdescribe;
	private BigDecimal istop;
	private Date creattime;
	private Date modifytime;
	private String spic;

	public Tgoods() {
	}

	public Tgoods(BigDecimal id) {
		this.id = id;
	}

	public Tgoods(BigDecimal id, Tuser tuserByCreatuser,
			Tuser tuserByModifyuser, Tcategorysecond tcategorysecond,
			String goodsname, BigDecimal price, BigDecimal sucount,
			BigDecimal transprice, String remaintime, BigDecimal salecount,
			BigDecimal sumsalecount, String goodsqutity, String belongto,
			BigDecimal hitcount, String gdescribe, BigDecimal istop,
			Date creattime, Date modifytime, String spic) {
		this.id = id;
		this.tuserByCreatuser = tuserByCreatuser;
		this.tuserByModifyuser = tuserByModifyuser;
		this.tcategorysecond = tcategorysecond;
		this.goodsname = goodsname;
		this.price = price;
		this.sucount = sucount;
		this.transprice = transprice;
		this.remaintime = remaintime;
		this.salecount = salecount;
		this.sumsalecount = sumsalecount;
		this.goodsqutity = goodsqutity;
		this.belongto = belongto;
		this.hitcount = hitcount;
		this.gdescribe = gdescribe;
		this.istop = istop;
		this.creattime = creattime;
		this.modifytime = modifytime;
		this.spic = spic;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Tuser getTuserByCreatuser() {
		return this.tuserByCreatuser;
	}

	public void setTuserByCreatuser(Tuser tuserByCreatuser) {
		this.tuserByCreatuser = tuserByCreatuser;
	}

	public Tuser getTuserByModifyuser() {
		return this.tuserByModifyuser;
	}

	public void setTuserByModifyuser(Tuser tuserByModifyuser) {
		this.tuserByModifyuser = tuserByModifyuser;
	}

	public Tcategorysecond getTcategorysecond() {
		return this.tcategorysecond;
	}

	public void setTcategorysecond(Tcategorysecond tcategorysecond) {
		this.tcategorysecond = tcategorysecond;
	}

	public String getGoodsname() {
		return this.goodsname;
	}

	public void setGoodsname(String goodsname) {
		this.goodsname = goodsname;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public BigDecimal getSucount() {
		return this.sucount;
	}

	public void setSucount(BigDecimal sucount) {
		this.sucount = sucount;
	}

	public BigDecimal getTransprice() {
		return this.transprice;
	}

	public void setTransprice(BigDecimal transprice) {
		this.transprice = transprice;
	}

	public String getRemaintime() {
		return this.remaintime;
	}

	public void setRemaintime(String remaintime) {
		this.remaintime = remaintime;
	}

	public BigDecimal getSalecount() {
		return this.salecount;
	}

	public void setSalecount(BigDecimal salecount) {
		this.salecount = salecount;
	}

	public BigDecimal getSumsalecount() {
		return this.sumsalecount;
	}

	public void setSumsalecount(BigDecimal sumsalecount) {
		this.sumsalecount = sumsalecount;
	}

	public String getGoodsqutity() {
		return this.goodsqutity;
	}

	public void setGoodsqutity(String goodsqutity) {
		this.goodsqutity = goodsqutity;
	}

	public String getBelongto() {
		return this.belongto;
	}

	public void setBelongto(String belongto) {
		this.belongto = belongto;
	}

	public BigDecimal getHitcount() {
		return this.hitcount;
	}

	public void setHitcount(BigDecimal hitcount) {
		this.hitcount = hitcount;
	}

	public String getGdescribe() {
		return this.gdescribe;
	}

	public void setGdescribe(String gdescribe) {
		this.gdescribe = gdescribe;
	}

	public BigDecimal getIstop() {
		return this.istop;
	}

	public void setIstop(BigDecimal istop) {
		this.istop = istop;
	}

	public Date getCreattime() {
		return this.creattime;
	}

	public void setCreattime(Date creattime) {
		this.creattime = creattime;
	}

	public Date getModifytime() {
		return this.modifytime;
	}

	public void setModifytime(Date modifytime) {
		this.modifytime = modifytime;
	}

	public String getSpic() {
		return this.spic;
	}

	public void setSpic(String spic) {
		this.spic = spic;
	}

}
