package pojo;

// Generated 2017-9-20 13:42:34 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * Tgoodspic generated by hbm2java
 */
public class Tgoodspic implements java.io.Serializable {

	private BigDecimal id;
	private Tuser tuserByModifyuser;
	private Tuser tuserByCreateuser;
	private BigDecimal goodsid;
	private BigDecimal pictype;
	private String picurl;
	private Date createtime;
	private Date modifytime;

	public Tgoodspic() {
	}

	public Tgoodspic(BigDecimal id) {
		this.id = id;
	}

	public Tgoodspic(BigDecimal id, Tuser tuserByModifyuser,
			Tuser tuserByCreateuser, BigDecimal goodsid, BigDecimal pictype,
			String picurl, Date createtime, Date modifytime) {
		this.id = id;
		this.tuserByModifyuser = tuserByModifyuser;
		this.tuserByCreateuser = tuserByCreateuser;
		this.goodsid = goodsid;
		this.pictype = pictype;
		this.picurl = picurl;
		this.createtime = createtime;
		this.modifytime = modifytime;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Tuser getTuserByModifyuser() {
		return this.tuserByModifyuser;
	}

	public void setTuserByModifyuser(Tuser tuserByModifyuser) {
		this.tuserByModifyuser = tuserByModifyuser;
	}

	public Tuser getTuserByCreateuser() {
		return this.tuserByCreateuser;
	}

	public void setTuserByCreateuser(Tuser tuserByCreateuser) {
		this.tuserByCreateuser = tuserByCreateuser;
	}

	public BigDecimal getGoodsid() {
		return this.goodsid;
	}

	public void setGoodsid(BigDecimal goodsid) {
		this.goodsid = goodsid;
	}

	public BigDecimal getPictype() {
		return this.pictype;
	}

	public void setPictype(BigDecimal pictype) {
		this.pictype = pictype;
	}

	public String getPicurl() {
		return this.picurl;
	}

	public void setPicurl(String picurl) {
		this.picurl = picurl;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Date getModifytime() {
		return this.modifytime;
	}

	public void setModifytime(Date modifytime) {
		this.modifytime = modifytime;
	}

}
