package pojo;

// Generated 2017-9-20 13:42:34 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * Tgoodsdiscount generated by hbm2java
 */
public class Tgoodsdiscount implements java.io.Serializable {

	private BigDecimal id;
	private Tuser tuserByModifyuser;
	private Tuser tuserByCreateuser;
	private BigDecimal goodsid;
	private BigDecimal discount;
	private Date createtime;
	private Date modifytime;

	public Tgoodsdiscount() {
	}

	public Tgoodsdiscount(BigDecimal id) {
		this.id = id;
	}

	public Tgoodsdiscount(BigDecimal id, Tuser tuserByModifyuser,
			Tuser tuserByCreateuser, BigDecimal goodsid, BigDecimal discount,
			Date createtime, Date modifytime) {
		this.id = id;
		this.tuserByModifyuser = tuserByModifyuser;
		this.tuserByCreateuser = tuserByCreateuser;
		this.goodsid = goodsid;
		this.discount = discount;
		this.createtime = createtime;
		this.modifytime = modifytime;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Tuser getTuserByModifyuser() {
		return this.tuserByModifyuser;
	}

	public void setTuserByModifyuser(Tuser tuserByModifyuser) {
		this.tuserByModifyuser = tuserByModifyuser;
	}

	public Tuser getTuserByCreateuser() {
		return this.tuserByCreateuser;
	}

	public void setTuserByCreateuser(Tuser tuserByCreateuser) {
		this.tuserByCreateuser = tuserByCreateuser;
	}

	public BigDecimal getGoodsid() {
		return this.goodsid;
	}

	public void setGoodsid(BigDecimal goodsid) {
		this.goodsid = goodsid;
	}

	public BigDecimal getDiscount() {
		return this.discount;
	}

	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Date getModifytime() {
		return this.modifytime;
	}

	public void setModifytime(Date modifytime) {
		this.modifytime = modifytime;
	}

}
