package pojo;

// Generated 2017-9-20 13:42:34 by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;
import java.util.Date;

/**
 * Torderdetail generated by hbm2java
 */
public class Torderdetail implements java.io.Serializable {

	private BigDecimal id;
	private BigDecimal orderid;
	private BigDecimal goodsid;
	private BigDecimal price;
	private BigDecimal counts;
	private BigDecimal state;
	private Date sendtime;

	public Torderdetail() {
	}

	public Torderdetail(BigDecimal id) {
		this.id = id;
	}

	public Torderdetail(BigDecimal id, BigDecimal orderid, BigDecimal goodsid,
			BigDecimal price, BigDecimal counts, BigDecimal state, Date sendtime) {
		this.id = id;
		this.orderid = orderid;
		this.goodsid = goodsid;
		this.price = price;
		this.counts = counts;
		this.state = state;
		this.sendtime = sendtime;
	}

	public BigDecimal getId() {
		return this.id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public BigDecimal getOrderid() {
		return this.orderid;
	}

	public void setOrderid(BigDecimal orderid) {
		this.orderid = orderid;
	}

	public BigDecimal getGoodsid() {
		return this.goodsid;
	}

	public void setGoodsid(BigDecimal goodsid) {
		this.goodsid = goodsid;
	}

	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	public BigDecimal getCounts() {
		return this.counts;
	}

	public void setCounts(BigDecimal counts) {
		this.counts = counts;
	}

	public BigDecimal getState() {
		return this.state;
	}

	public void setState(BigDecimal state) {
		this.state = state;
	}

	public Date getSendtime() {
		return this.sendtime;
	}

	public void setSendtime(Date sendtime) {
		this.sendtime = sendtime;
	}

}
