package pojo;

// Generated 2017-9-20 13:42:34 by Hibernate Tools 3.2.2.GA

 
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tuser generated by hbm2java
 */
public class Tuser implements java.io.Serializable {

	private java.lang.Long id;
	private String loginname;
	private String realname;
	private String password;
	private java.lang.Long sex;
	private Date birthday;
	private String cardid;
	private String email;
	private String tel;
	private String address;
	private java.lang.Long isuse;
	private java.lang.Long creatuser;
	private Date creattime;
	private java.lang.Long modifyuser;
	private Date modifytime;
	private Set tcategoryseconds = new HashSet(0);
	private Set tcategoriesForModifyuser = new HashSet(0);
	private Set tgoodspicsForModifyuser = new HashSet(0);
	private Set tcategoriesForCreatuser = new HashSet(0);
	private Set tannouncementsForModifyuser = new HashSet(0);
	private Set tsyslogs = new HashSet(0);
	private Set tgoodsdiscountsForModifyuser = new HashSet(0);
	private Set tgoodsesForModifyuser = new HashSet(0);
	private Set tannouncementsForCreatuser = new HashSet(0);
	private Set tgoodsdiscountsForCreateuser = new HashSet(0);
	private Set tgoodspicsForCreateuser = new HashSet(0);
	private Set tgoodsesForCreatuser = new HashSet(0);

	public Tuser() {
	}

	public Tuser(java.lang.Long id) {
		this.id = id;
	}

	public Tuser(java.lang.Long id, String loginname, String realname,
			String password, java.lang.Long sex, Date birthday, String cardid,
			String email, String tel, String address, java.lang.Long isuse,
			java.lang.Long creatuser, Date creattime, java.lang.Long modifyuser,
			Date modifytime, Set tcategoryseconds,
			Set tcategoriesForModifyuser, Set tgoodspicsForModifyuser,
			Set tcategoriesForCreatuser, Set tannouncementsForModifyuser,
			Set tsyslogs, Set tgoodsdiscountsForModifyuser,
			Set tgoodsesForModifyuser, Set tannouncementsForCreatuser,
			Set tgoodsdiscountsForCreateuser, Set tgoodspicsForCreateuser,
			Set tgoodsesForCreatuser) {
		this.id = id;
		this.loginname = loginname;
		this.realname = realname;
		this.password = password;
		this.sex = sex;
		this.birthday = birthday;
		this.cardid = cardid;
		this.email = email;
		this.tel = tel;
		this.address = address;
		this.isuse = isuse;
		this.creatuser = creatuser;
		this.creattime = creattime;
		this.modifyuser = modifyuser;
		this.modifytime = modifytime;
		this.tcategoryseconds = tcategoryseconds;
		this.tcategoriesForModifyuser = tcategoriesForModifyuser;
		this.tgoodspicsForModifyuser = tgoodspicsForModifyuser;
		this.tcategoriesForCreatuser = tcategoriesForCreatuser;
		this.tannouncementsForModifyuser = tannouncementsForModifyuser;
		this.tsyslogs = tsyslogs;
		this.tgoodsdiscountsForModifyuser = tgoodsdiscountsForModifyuser;
		this.tgoodsesForModifyuser = tgoodsesForModifyuser;
		this.tannouncementsForCreatuser = tannouncementsForCreatuser;
		this.tgoodsdiscountsForCreateuser = tgoodsdiscountsForCreateuser;
		this.tgoodspicsForCreateuser = tgoodspicsForCreateuser;
		this.tgoodsesForCreatuser = tgoodsesForCreatuser;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public String getLoginname() {
		return this.loginname;
	}

	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	public String getRealname() {
		return this.realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public java.lang.Long getSex() {
		return this.sex;
	}

	public void setSex(java.lang.Long sex) {
		this.sex = sex;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getCardid() {
		return this.cardid;
	}

	public void setCardid(String cardid) {
		this.cardid = cardid;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public java.lang.Long getIsuse() {
		return this.isuse;
	}

	public void setIsuse(java.lang.Long isuse) {
		this.isuse = isuse;
	}

	public java.lang.Long getCreatuser() {
		return this.creatuser;
	}

	public void setCreatuser(java.lang.Long creatuser) {
		this.creatuser = creatuser;
	}

	public Date getCreattime() {
		return this.creattime;
	}

	public void setCreattime(Date creattime) {
		this.creattime = creattime;
	}

	public java.lang.Long getModifyuser() {
		return this.modifyuser;
	}

	public void setModifyuser(java.lang.Long modifyuser) {
		this.modifyuser = modifyuser;
	}

	public Date getModifytime() {
		return this.modifytime;
	}

	public void setModifytime(Date modifytime) {
		this.modifytime = modifytime;
	}

	public Set getTcategoryseconds() {
		return this.tcategoryseconds;
	}

	public void setTcategoryseconds(Set tcategoryseconds) {
		this.tcategoryseconds = tcategoryseconds;
	}

	public Set getTcategoriesForModifyuser() {
		return this.tcategoriesForModifyuser;
	}

	public void setTcategoriesForModifyuser(Set tcategoriesForModifyuser) {
		this.tcategoriesForModifyuser = tcategoriesForModifyuser;
	}

	public Set getTgoodspicsForModifyuser() {
		return this.tgoodspicsForModifyuser;
	}

	public void setTgoodspicsForModifyuser(Set tgoodspicsForModifyuser) {
		this.tgoodspicsForModifyuser = tgoodspicsForModifyuser;
	}

	public Set getTcategoriesForCreatuser() {
		return this.tcategoriesForCreatuser;
	}

	public void setTcategoriesForCreatuser(Set tcategoriesForCreatuser) {
		this.tcategoriesForCreatuser = tcategoriesForCreatuser;
	}

	public Set getTannouncementsForModifyuser() {
		return this.tannouncementsForModifyuser;
	}

	public void setTannouncementsForModifyuser(Set tannouncementsForModifyuser) {
		this.tannouncementsForModifyuser = tannouncementsForModifyuser;
	}

	public Set getTsyslogs() {
		return this.tsyslogs;
	}

	public void setTsyslogs(Set tsyslogs) {
		this.tsyslogs = tsyslogs;
	}

	public Set getTgoodsdiscountsForModifyuser() {
		return this.tgoodsdiscountsForModifyuser;
	}

	public void setTgoodsdiscountsForModifyuser(Set tgoodsdiscountsForModifyuser) {
		this.tgoodsdiscountsForModifyuser = tgoodsdiscountsForModifyuser;
	}

	public Set getTgoodsesForModifyuser() {
		return this.tgoodsesForModifyuser;
	}

	public void setTgoodsesForModifyuser(Set tgoodsesForModifyuser) {
		this.tgoodsesForModifyuser = tgoodsesForModifyuser;
	}

	public Set getTannouncementsForCreatuser() {
		return this.tannouncementsForCreatuser;
	}

	public void setTannouncementsForCreatuser(Set tannouncementsForCreatuser) {
		this.tannouncementsForCreatuser = tannouncementsForCreatuser;
	}

	public Set getTgoodsdiscountsForCreateuser() {
		return this.tgoodsdiscountsForCreateuser;
	}

	public void setTgoodsdiscountsForCreateuser(Set tgoodsdiscountsForCreateuser) {
		this.tgoodsdiscountsForCreateuser = tgoodsdiscountsForCreateuser;
	}

	public Set getTgoodspicsForCreateuser() {
		return this.tgoodspicsForCreateuser;
	}

	public void setTgoodspicsForCreateuser(Set tgoodspicsForCreateuser) {
		this.tgoodspicsForCreateuser = tgoodspicsForCreateuser;
	}

	public Set getTgoodsesForCreatuser() {
		return this.tgoodsesForCreatuser;
	}

	public void setTgoodsesForCreatuser(Set tgoodsesForCreatuser) {
		this.tgoodsesForCreatuser = tgoodsesForCreatuser;
	}

}
