package sousuo.entity;

import java.sql.Date;
import java.util.List;

// default package
// Generated 2017-7-24 17:05:53 by Hibernate Tools 3.2.2.GA

/**
 * Tcategory generated by hbm2java
 */
public class Tcategory implements java.io.Serializable {

	private Integer id;
	private String catename;
	private Integer creatuser;
	private List<Tcategorysecond> smalls;
	public List<Tcategorysecond> getSmalls() {
		return smalls;
	}

	public void setSmalls(List<Tcategorysecond> smalls) {
		this.smalls = smalls;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	private Date createtime;
	private Integer modifyuser;
	private Date modifytime;

	public Tcategory() {
	}

	public Tcategory(String catename, Integer creatuser, Date createtime,
			Integer modifyuser, Date modifytime) {
		this.catename = catename;
		this.creatuser = creatuser;
		this.createtime = createtime;
		this.modifyuser = modifyuser;
		this.modifytime = modifytime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCatename() {
		return this.catename;
	}

	public void setCatename(String catename) {
		this.catename = catename;
	}

	public Integer getCreatuser() {
		return this.creatuser;
	}

	public void setCreatuser(Integer creatuser) {
		this.creatuser = creatuser;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreattime(Date createtime) {
		this.createtime = createtime;
	}

	public Integer getModifyuser() {
		return this.modifyuser;
	}

	public void setModifyuser(Integer modifyuser) {
		this.modifyuser = modifyuser;
	}

	public Date getModifytime() {
		return this.modifytime;
	}

	public void setModifytime(Date modifytime) {
		this.modifytime = modifytime;
	}

}
