package sousuo.entity;

import java.sql.Date;

// default package
// Generated 2017-7-24 17:05:53 by Hibernate Tools 3.2.2.GA

/**
 * Tcategorysecond generated by hbm2java
 */
public class Tcategorysecond implements java.io.Serializable {

	private Integer id;
	private String catesname;
	private Integer pid;
	public Integer getPid() {
		return pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	private Integer creatuser;
	private Date creattime;
	 

	 

	public Date getCreattime() {
		return creattime;
	}

	public void setCreattime(Date creattime) {
		this.creattime = creattime;
	}

	private Integer modifyuser;
	private Date modifytime;
	private String catename;// 大分类名称

	public String getCatename() {
		return catename;
	}

	public void setCatename(String catename) {
		this.catename = catename;
	}

	public Tcategorysecond() {
	}

	public Tcategorysecond(String catesname, Integer pid, Integer creatuser,
			Date creattime, Integer modifyuser, Date modifytime, String catename) {
		this.catesname = catesname;
		this.pid = pid;
		this.creatuser = creatuser;
		this.creattime = creattime;
		this.modifyuser = modifyuser;
		this.modifytime = modifytime;
		this.catename = catename;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getCatesname() {
		return this.catesname;
	}

	public void setCatesname(String catesname) {
		this.catesname = catesname;
	}

	 

	public Integer getCreatuser() {
		return this.creatuser;
	}

	public void setCreatuser(Integer creatuser) {
		this.creatuser = creatuser;
	}

	 

	public Integer getModifyuser() {
		return this.modifyuser;
	}

	public void setModifyuser(Integer modifyuser) {
		this.modifyuser = modifyuser;
	}

	public Date getModifytime() {
		return this.modifytime;
	}

	public void setModifytime(Date modifytime) {
		this.modifytime = modifytime;
	}

}
