package com.lechenggu.tannouncement.entity;

// default package
// Generated 2017-7-24 17:05:53 by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * Tannouncement generated by hbm2java
 */
public class Tannouncement implements java.io.Serializable {

	private Integer id;
	private String anntitle;
	private String anncontext;
	private Integer creatuser;
	private Date creattime;
	private Integer modifyuser;
	private Date modifytime;

	public Tannouncement() {
	}

	public Tannouncement(String anntitle, String anncontext, Integer creatuser,
			Date creattime, Integer modifyuser, Date modifytime) {
		this.anntitle = anntitle;
		this.anncontext = anncontext;
		this.creatuser = creatuser;
		this.creattime = creattime;
		this.modifyuser = modifyuser;
		this.modifytime = modifytime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAnntitle() {
		return this.anntitle;
	}

	public void setAnntitle(String anntitle) {
		this.anntitle = anntitle;
	}

	public String getAnncontext() {
		return this.anncontext;
	}

	public void setAnncontext(String anncontext) {
		this.anncontext = anncontext;
	}

	public Integer getCreatuser() {
		return this.creatuser;
	}

	public void setCreatuser(Integer creatuser) {
		this.creatuser = creatuser;
	}

	public Date getCreattime() {
		return this.creattime;
	}

	public void setCreattime(Date creattime) {
		this.creattime = creattime;
	}

	public Integer getModifyuser() {
		return this.modifyuser;
	}

	public void setModifyuser(Integer modifyuser) {
		this.modifyuser = modifyuser;
	}

	public Date getModifytime() {
		return this.modifytime;
	}

	public void setModifytime(Date modifytime) {
		this.modifytime = modifytime;
	}

}
